### ISSUE TITLE
Desenvolver versão MacOS

### ISSUE THREAD

**Issue by rebeccamello** [Rebeccompany/Project-Swift#309]
- [x] Sidebar
- [x] Tela de decks
- [x] Tela de flashcards
- [ ] Tela de estudo
- [x] Formulário de flashcard
- [x] Chamada do formulário de criar nova coleção / editar coleção
- [x] Chamada do formulário de criar nova deck / editar deck
- [x] Testes das novas funções
- [ ]  Tela de import

**Comment by gbrlCM** [comment]
Primeiramente corrigir erros de compatibilidade com o MacOS, depois realizar pequenas alterações e por ultimo alterações no fluxo e arquitetura caso necessário
