### ISSUE TITLE
Desenvolver a tela de decks - GRID

### ISSUE THREAD

**Issue by rebeccamello** [Rebeccompany/Project-Swift#35]
- [x] View
- [x] iPad
- [x] View Model
- [x] Testes
- [x] Acessibilidade

**Comment by gbrlCM** [comment]
# Requisitos

- [ ] Agrupar por Sections de Grupos, e Outros
- [ ] Botão de + da tool adiciona um Deck sem coleção
- [ ] Botão de + de uma coleção adiciona um deck novo aquela coleção
- [ ] Caso não tenha um deck Empty State com um botão grande e visível para criar um novo Deck sem Grupo

![Image](https://user-images.githubusercontent.com/60374568/190178293-c5f937df-3847-4cca-8f6a-0b91f646e80e.png)

![Image](https://user-images.githubusercontent.com/60374568/190178439-6023f01b-a4ff-4fd0-a55c-03c831e18a87.png)
