### ISSUE TITLE
[DESIGN] [TSK - 3] Desenvolver componentes do fluxo de estudo

### ISSUE THREAD

**Issue by rebeccamello** [Rebeccompany/Project-Swift#54]
- [ ] Componente de Flashcard
- [ ] Componente de Botão
- [ ] Componente de "Deck" de Flashcards

## Criterios de aceite
- [ ] Acessibilidade Voice Over e Tamanho de texto
- [ ] Animações e estados de habilitado e desabilitado
- [ ] Componentização

**Comment by gbrlCM** [comment]
### Acessibilidade texto gigante
![Image](https://user-images.githubusercontent.com/60374568/188467166-f4bdc674-b8c5-4772-ac1e-a4f599c14e0a.png)

**Comment by gbrlCM** [comment]
### Texto tamanho normal

![Image](https://user-images.githubusercontent.com/60374568/188468685-b1fb8c82-c096-4f4a-abf4-16c32f8c16d4.png)
